### ISSUE TITLE
"Invalid key constant: {"

### ISSUE THREAD

**Issue by maxiy01** [flamendless/lovedebug#1]
Hello, I can't enter '{', '}', '~' characters in console, as there is no such KeyConstants in love2d.
Error: lovedebug.lua:724: Invalid key constant: {

**Comment by flamendless** [comment]
Hi, those keys are unlisted in the love [keyConstants](https://love2d.org/wiki/KeyConstant) and [Scancode](https://love2d.org/wiki/Scancode).

But it I can monkey patch the source code of lovedebug to support those.

**Comment by flamendless** [comment]
hi, this is now fixed by commit https://github.com/flamendless/lovedebug/commit/b11f5f1ca1e3a0b15d74c483011a74e60c35dc18
